//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("workstation id=MAINAMDB.mssql.somee.com;packet size=4096;user id=mainam_SQLLogin_" +
            "1;pwd=b463clsihk;data source=MAINAMDB.mssql.somee.com;persist security info=Fals" +
            "e;initial catalog=MAINAMDB")]
        public string DBTestConnectionString {
            get {
                return ((string)(this["DBTestConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MAINAMDB.mssql.somee.com;Initial Catalog=MAINAMDB;Persist Security In" +
            "fo=False;User ID=mainam_SQLLogin_1;Password=b463clsihk;Packet Size=4096;Workstat" +
            "ion ID=MAINAMDB.mssql.somee.com")]
        public string MAINAMDBConnectionString {
            get {
                return ((string)(this["MAINAMDBConnectionString"]));
            }
        }
    }
}
