<?xml version="1.0" encoding="utf-8"?><Database Name="wdmfglrf_SOCIAL_NETWORK" Class="UserDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=103.48.81.23;Initial Catalog=wdmfglrf_SOCIAL_NETWORK;Persist Security Info=True;User ID=wdmfglrf_mainam" SettingsObjectName="DataAccess.Properties.Settings" SettingsPropertyName="wdmfglrf_SOCIAL_NETWORKConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tbUser" Member="tbUsers">
    <Type Name="tbUser">
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Token" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>