#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MAINAMDB")]
	public partial class IPDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public IPDbDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.MAINAMDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public IPDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IPDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IPDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public IPDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<IPLOCATION> IPLOCATIONs
		{
			get
			{
				return this.GetTable<IPLOCATION>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IPLOCATION")]
	public partial class IPLOCATION
	{
		
		private double _IP_FROM;
		
		private double _IP_TO;
		
		private string _COUNTRY_CODE;
		
		private string _COUNTRY_NAME;
		
		public IPLOCATION()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_FROM", DbType="Float NOT NULL")]
		public double IP_FROM
		{
			get
			{
				return this._IP_FROM;
			}
			set
			{
				if ((this._IP_FROM != value))
				{
					this._IP_FROM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IP_TO", DbType="Float NOT NULL")]
		public double IP_TO
		{
			get
			{
				return this._IP_TO;
			}
			set
			{
				if ((this._IP_TO != value))
				{
					this._IP_TO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY_CODE", DbType="NVarChar(2) NOT NULL", CanBeNull=false)]
		public string COUNTRY_CODE
		{
			get
			{
				return this._COUNTRY_CODE;
			}
			set
			{
				if ((this._COUNTRY_CODE != value))
				{
					this._COUNTRY_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY_NAME", DbType="NVarChar(64) NOT NULL", CanBeNull=false)]
		public string COUNTRY_NAME
		{
			get
			{
				return this._COUNTRY_NAME;
			}
			set
			{
				if ((this._COUNTRY_NAME != value))
				{
					this._COUNTRY_NAME = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
