#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MAINAMDB")]
	public partial class OfferDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOFFER(OFFER instance);
    partial void UpdateOFFER(OFFER instance);
    partial void DeleteOFFER(OFFER instance);
    #endregion
		
		public OfferDbDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.DBTestConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OfferDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OfferDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OfferDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OfferDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OFFER> OFFERs
		{
			get
			{
				return this.GetTable<OFFER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OFFER")]
	public partial class OFFER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _OFFER_ID;
		
		private string _OFFER_NAME;
		
		private string _OFFER_COUNTRY;
		
		private string _OFFER_TRACKING;
		
		private string _OFFER_REVIEW;
		
		private string _OFFER_ICON;
		
		private string _OFFER_PAYOUT;
		
		private int _OFFER_POINT;
		
		private System.Nullable<int> _OFFER_DOWNLOAD;
		
		private System.Nullable<double> _OFFER_RATE;
		
		private bool _OFFER_STATUS;
		
		private System.Nullable<System.DateTime> _OFFER_EXPIRE;
		
		private string _META_KEY;
		
		private int _NET_ID;
		
		private string _CATE_NAME;
		
		private int _FLATFORM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnOFFER_IDChanging(string value);
    partial void OnOFFER_IDChanged();
    partial void OnOFFER_NAMEChanging(string value);
    partial void OnOFFER_NAMEChanged();
    partial void OnOFFER_COUNTRYChanging(string value);
    partial void OnOFFER_COUNTRYChanged();
    partial void OnOFFER_TRACKINGChanging(string value);
    partial void OnOFFER_TRACKINGChanged();
    partial void OnOFFER_REVIEWChanging(string value);
    partial void OnOFFER_REVIEWChanged();
    partial void OnOFFER_ICONChanging(string value);
    partial void OnOFFER_ICONChanged();
    partial void OnOFFER_PAYOUTChanging(string value);
    partial void OnOFFER_PAYOUTChanged();
    partial void OnOFFER_POINTChanging(int value);
    partial void OnOFFER_POINTChanged();
    partial void OnOFFER_DOWNLOADChanging(System.Nullable<int> value);
    partial void OnOFFER_DOWNLOADChanged();
    partial void OnOFFER_RATEChanging(System.Nullable<double> value);
    partial void OnOFFER_RATEChanged();
    partial void OnOFFER_STATUSChanging(bool value);
    partial void OnOFFER_STATUSChanged();
    partial void OnOFFER_EXPIREChanging(System.Nullable<System.DateTime> value);
    partial void OnOFFER_EXPIREChanged();
    partial void OnMETA_KEYChanging(string value);
    partial void OnMETA_KEYChanged();
    partial void OnNET_IDChanging(int value);
    partial void OnNET_IDChanged();
    partial void OnCATE_NAMEChanging(string value);
    partial void OnCATE_NAMEChanged();
    partial void OnFLATFORMChanging(int value);
    partial void OnFLATFORMChanged();
    #endregion
		
		public OFFER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string OFFER_ID
		{
			get
			{
				return this._OFFER_ID;
			}
			set
			{
				if ((this._OFFER_ID != value))
				{
					this.OnOFFER_IDChanging(value);
					this.SendPropertyChanging();
					this._OFFER_ID = value;
					this.SendPropertyChanged("OFFER_ID");
					this.OnOFFER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string OFFER_NAME
		{
			get
			{
				return this._OFFER_NAME;
			}
			set
			{
				if ((this._OFFER_NAME != value))
				{
					this.OnOFFER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._OFFER_NAME = value;
					this.SendPropertyChanged("OFFER_NAME");
					this.OnOFFER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_COUNTRY", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string OFFER_COUNTRY
		{
			get
			{
				return this._OFFER_COUNTRY;
			}
			set
			{
				if ((this._OFFER_COUNTRY != value))
				{
					this.OnOFFER_COUNTRYChanging(value);
					this.SendPropertyChanging();
					this._OFFER_COUNTRY = value;
					this.SendPropertyChanged("OFFER_COUNTRY");
					this.OnOFFER_COUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_TRACKING", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string OFFER_TRACKING
		{
			get
			{
				return this._OFFER_TRACKING;
			}
			set
			{
				if ((this._OFFER_TRACKING != value))
				{
					this.OnOFFER_TRACKINGChanging(value);
					this.SendPropertyChanging();
					this._OFFER_TRACKING = value;
					this.SendPropertyChanged("OFFER_TRACKING");
					this.OnOFFER_TRACKINGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_REVIEW", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string OFFER_REVIEW
		{
			get
			{
				return this._OFFER_REVIEW;
			}
			set
			{
				if ((this._OFFER_REVIEW != value))
				{
					this.OnOFFER_REVIEWChanging(value);
					this.SendPropertyChanging();
					this._OFFER_REVIEW = value;
					this.SendPropertyChanged("OFFER_REVIEW");
					this.OnOFFER_REVIEWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_ICON", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string OFFER_ICON
		{
			get
			{
				return this._OFFER_ICON;
			}
			set
			{
				if ((this._OFFER_ICON != value))
				{
					this.OnOFFER_ICONChanging(value);
					this.SendPropertyChanging();
					this._OFFER_ICON = value;
					this.SendPropertyChanged("OFFER_ICON");
					this.OnOFFER_ICONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_PAYOUT", DbType="NVarChar(50)")]
		public string OFFER_PAYOUT
		{
			get
			{
				return this._OFFER_PAYOUT;
			}
			set
			{
				if ((this._OFFER_PAYOUT != value))
				{
					this.OnOFFER_PAYOUTChanging(value);
					this.SendPropertyChanging();
					this._OFFER_PAYOUT = value;
					this.SendPropertyChanged("OFFER_PAYOUT");
					this.OnOFFER_PAYOUTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_POINT", DbType="Int NOT NULL")]
		public int OFFER_POINT
		{
			get
			{
				return this._OFFER_POINT;
			}
			set
			{
				if ((this._OFFER_POINT != value))
				{
					this.OnOFFER_POINTChanging(value);
					this.SendPropertyChanging();
					this._OFFER_POINT = value;
					this.SendPropertyChanged("OFFER_POINT");
					this.OnOFFER_POINTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_DOWNLOAD", DbType="Int")]
		public System.Nullable<int> OFFER_DOWNLOAD
		{
			get
			{
				return this._OFFER_DOWNLOAD;
			}
			set
			{
				if ((this._OFFER_DOWNLOAD != value))
				{
					this.OnOFFER_DOWNLOADChanging(value);
					this.SendPropertyChanging();
					this._OFFER_DOWNLOAD = value;
					this.SendPropertyChanged("OFFER_DOWNLOAD");
					this.OnOFFER_DOWNLOADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_RATE", DbType="Float")]
		public System.Nullable<double> OFFER_RATE
		{
			get
			{
				return this._OFFER_RATE;
			}
			set
			{
				if ((this._OFFER_RATE != value))
				{
					this.OnOFFER_RATEChanging(value);
					this.SendPropertyChanging();
					this._OFFER_RATE = value;
					this.SendPropertyChanged("OFFER_RATE");
					this.OnOFFER_RATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_STATUS", DbType="Bit NOT NULL")]
		public bool OFFER_STATUS
		{
			get
			{
				return this._OFFER_STATUS;
			}
			set
			{
				if ((this._OFFER_STATUS != value))
				{
					this.OnOFFER_STATUSChanging(value);
					this.SendPropertyChanging();
					this._OFFER_STATUS = value;
					this.SendPropertyChanged("OFFER_STATUS");
					this.OnOFFER_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OFFER_EXPIRE", DbType="DateTime")]
		public System.Nullable<System.DateTime> OFFER_EXPIRE
		{
			get
			{
				return this._OFFER_EXPIRE;
			}
			set
			{
				if ((this._OFFER_EXPIRE != value))
				{
					this.OnOFFER_EXPIREChanging(value);
					this.SendPropertyChanging();
					this._OFFER_EXPIRE = value;
					this.SendPropertyChanged("OFFER_EXPIRE");
					this.OnOFFER_EXPIREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_META_KEY", DbType="VarChar(250)")]
		public string META_KEY
		{
			get
			{
				return this._META_KEY;
			}
			set
			{
				if ((this._META_KEY != value))
				{
					this.OnMETA_KEYChanging(value);
					this.SendPropertyChanging();
					this._META_KEY = value;
					this.SendPropertyChanged("META_KEY");
					this.OnMETA_KEYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET_ID", DbType="Int NOT NULL")]
		public int NET_ID
		{
			get
			{
				return this._NET_ID;
			}
			set
			{
				if ((this._NET_ID != value))
				{
					this.OnNET_IDChanging(value);
					this.SendPropertyChanging();
					this._NET_ID = value;
					this.SendPropertyChanged("NET_ID");
					this.OnNET_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CATE_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string CATE_NAME
		{
			get
			{
				return this._CATE_NAME;
			}
			set
			{
				if ((this._CATE_NAME != value))
				{
					this.OnCATE_NAMEChanging(value);
					this.SendPropertyChanging();
					this._CATE_NAME = value;
					this.SendPropertyChanged("CATE_NAME");
					this.OnCATE_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLATFORM", DbType="Int NOT NULL")]
		public int FLATFORM
		{
			get
			{
				return this._FLATFORM;
			}
			set
			{
				if ((this._FLATFORM != value))
				{
					this.OnFLATFORMChanging(value);
					this.SendPropertyChanging();
					this._FLATFORM = value;
					this.SendPropertyChanged("FLATFORM");
					this.OnFLATFORMChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
