#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MAINAMDB")]
	public partial class UserDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMEMBER(MEMBER instance);
    partial void UpdateMEMBER(MEMBER instance);
    partial void DeleteMEMBER(MEMBER instance);
    #endregion
		
		public UserDbDataContext() : 
				base(global::DataAccess.Properties.Settings.Default.MAINAMDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public UserDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UserDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MEMBER> MEMBERs
		{
			get
			{
				return this.GetTable<MEMBER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MEMBER")]
	public partial class MEMBER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MEMBER_ID;
		
		private string _MEMBER_NAME;
		
		private string _MEMBER_PASSWORD;
		
		private bool _MEMBER_STATUS;
		
		private System.Nullable<int> _MEMBER_TOTAL_POINT;
		
		private System.Nullable<int> _MEMBER_PENDING_POINT;
		
		private System.Nullable<int> _MEMBER_CURRENT_POINT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMEMBER_IDChanging(string value);
    partial void OnMEMBER_IDChanged();
    partial void OnMEMBER_NAMEChanging(string value);
    partial void OnMEMBER_NAMEChanged();
    partial void OnMEMBER_PASSWORDChanging(string value);
    partial void OnMEMBER_PASSWORDChanged();
    partial void OnMEMBER_STATUSChanging(bool value);
    partial void OnMEMBER_STATUSChanged();
    partial void OnMEMBER_TOTAL_POINTChanging(System.Nullable<int> value);
    partial void OnMEMBER_TOTAL_POINTChanged();
    partial void OnMEMBER_PENDING_POINTChanging(System.Nullable<int> value);
    partial void OnMEMBER_PENDING_POINTChanged();
    partial void OnMEMBER_CURRENT_POINTChanging(System.Nullable<int> value);
    partial void OnMEMBER_CURRENT_POINTChanged();
    #endregion
		
		public MEMBER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_ID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MEMBER_ID
		{
			get
			{
				return this._MEMBER_ID;
			}
			set
			{
				if ((this._MEMBER_ID != value))
				{
					this.OnMEMBER_IDChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_ID = value;
					this.SendPropertyChanged("MEMBER_ID");
					this.OnMEMBER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MEMBER_NAME
		{
			get
			{
				return this._MEMBER_NAME;
			}
			set
			{
				if ((this._MEMBER_NAME != value))
				{
					this.OnMEMBER_NAMEChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_NAME = value;
					this.SendPropertyChanged("MEMBER_NAME");
					this.OnMEMBER_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_PASSWORD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MEMBER_PASSWORD
		{
			get
			{
				return this._MEMBER_PASSWORD;
			}
			set
			{
				if ((this._MEMBER_PASSWORD != value))
				{
					this.OnMEMBER_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_PASSWORD = value;
					this.SendPropertyChanged("MEMBER_PASSWORD");
					this.OnMEMBER_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_STATUS", DbType="Bit NOT NULL")]
		public bool MEMBER_STATUS
		{
			get
			{
				return this._MEMBER_STATUS;
			}
			set
			{
				if ((this._MEMBER_STATUS != value))
				{
					this.OnMEMBER_STATUSChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_STATUS = value;
					this.SendPropertyChanged("MEMBER_STATUS");
					this.OnMEMBER_STATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_TOTAL_POINT", DbType="Int")]
		public System.Nullable<int> MEMBER_TOTAL_POINT
		{
			get
			{
				return this._MEMBER_TOTAL_POINT;
			}
			set
			{
				if ((this._MEMBER_TOTAL_POINT != value))
				{
					this.OnMEMBER_TOTAL_POINTChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_TOTAL_POINT = value;
					this.SendPropertyChanged("MEMBER_TOTAL_POINT");
					this.OnMEMBER_TOTAL_POINTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_PENDING_POINT", DbType="Int")]
		public System.Nullable<int> MEMBER_PENDING_POINT
		{
			get
			{
				return this._MEMBER_PENDING_POINT;
			}
			set
			{
				if ((this._MEMBER_PENDING_POINT != value))
				{
					this.OnMEMBER_PENDING_POINTChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_PENDING_POINT = value;
					this.SendPropertyChanged("MEMBER_PENDING_POINT");
					this.OnMEMBER_PENDING_POINTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEMBER_CURRENT_POINT", DbType="Int")]
		public System.Nullable<int> MEMBER_CURRENT_POINT
		{
			get
			{
				return this._MEMBER_CURRENT_POINT;
			}
			set
			{
				if ((this._MEMBER_CURRENT_POINT != value))
				{
					this.OnMEMBER_CURRENT_POINTChanging(value);
					this.SendPropertyChanging();
					this._MEMBER_CURRENT_POINT = value;
					this.SendPropertyChanged("MEMBER_CURRENT_POINT");
					this.OnMEMBER_CURRENT_POINTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
